[build]
  command = "npm run build"
  publish = "build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 